pluginManagement {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Fabric"
                    url = uri("https://maven.fabricmc.net/")
                }
            }
            filter {
                includeGroup("net.fabricmc")
                includeGroupByRegex('net\\.fabricmc\\..*')
            }
        }
        gradlePluginPortal()
    }
}

rootProject.name = "WaterSourceMod"
